### ISSUE TITLE
v4.11.0 (Sigel)

### ISSUE THREAD

**Issue by compomega** [comphack/comp_hack#1165]
This is a master issue listing all the related changes for the release.

# Code
* [x] Proper fix for diaspora base state upon relog (#1161)
* [x] BDPatch - add additional info to error message. (#1164)
* [x] Build the external dependencies with TravisCI (#968)

# Content
* [x] Shinagawa Catacombs: Gold (#849)
